spring:
  application:
    name: sec7
  config:
    import: application_test.yml, application_prod.yml
  profiles:
    active: prod, test
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:eazybank}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        show_sql: ${HIBERNATE_FORMAT_SQL:true}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:2m}

logging:
  level:
    org:
     springframework:
       security: ${SPRING_SECURITY_LOG_LEVEL:trace}